keybinding:
  universal:
    quit-alt1: '<disabled>' # alternative/alias of quit
    togglePanel: '<tab>' # goto the next panel
    prevItem-alt: 'i' # go one line up
    nextItem-alt: 'e' # go one line down
    scrollLeft: 'N' # scroll left within list view
    scrollRight: 'O' # scroll right within list view
    prevBlock: '<disabled>' # goto the previous block / panel
    nextBlock: '<disabled>' # goto the next block / panel
    prevBlock-alt: 'n' # goto the previous block / panel
    nextBlock-alt: 'o' # goto the next block / panel
    nextMatch: 's'
    prevMatch: 'S'
    new: '<c-n>'
    edit: '<c-e>'
    openFile: '<c-o>'
    scrollUpMain-alt1: 'I' # main panel scroll up
    scrollDownMain-alt1: 'E' # main panel scroll down
    nextTab: '<right>'
    prevTab: '<left>'
    undo: '<c-z>'
    redo: '<c-y>'
    diffingMenu: 'w'
    diffingMenu-alt: '<disabled>' # deprecated
    copyToClipboard: '<c-c>'
    toggleWhitespaceInDiffView: '<c-w>'

gui:
 # catppuccin mocha
  theme:
    activeBorderColor:
      - '#cba6f7'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#cba6f7'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'
