keybinding:
  universal:
    quit-alt1: '<disabled>' # alternative/alias of quit
    togglePanel: '<tab>' # goto the next panel
    prevItem-alt: 'i' # go one line up
    nextItem-alt: 'e' # go one line down
    scrollLeft: 'N' # scroll left within list view
    scrollRight: 'O' # scroll right within list view
    prevBlock: '<disabled>' # goto the previous block / panel
    nextBlock: '<disabled>' # goto the next block / panel
    prevBlock-alt: 'n' # goto the previous block / panel
    nextBlock-alt: 'o' # goto the next block / panel
    nextMatch: 's'
    prevMatch: 'S'
    openRecentRepos: '<c-r>'
    confirm: '<enter>'
    remove: 'd'
    new: '<c-n>'
    edit: '<c-e>'
    openFile: '<c-o>'
    scrollUpMain-alt1: 'K' # main panel scroll up
    scrollDownMain-alt1: 'J' # main panel scroll down
    nextTab: '<right>'
    prevTab: '<left>'
    undo: '<c-z>'
    redo: '<c-y>'
    diffingMenu: 'w'
    diffingMenu-alt: '<c-e>' # deprecated
    copyToClipboard: '<c-c>'
    toggleWhitespaceInDiffView: '<c-w>'
    rangeSelectUp: '<s-up>'
    rangeSelectDown: '<s-down>'
  status:
    checkForUpdate: 'u'
  files:
    commitChanges: 'c'
    commitChangesWithoutHook: '<disabled>' # commit changes without pre-commit hook
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    findBaseCommitForFixup: '<c-f>'
    confirmDiscard: 'x'
    ignoreFile: 'I'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a' # stage/unstage all
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
    openMergeTool: 'M'
    openStatusFilter: '<c-b>'
  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    renameBranch: 'R'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'I'
    fastForward: 'f' # fast-forward this branch from its upstream
    createTag: 'T'
    pushTag: 'P'
    setUpstream: 'u' # set as upstream of checked-out branch
    fetchRemote: 'f'
  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F' # create fixup commit for this commit
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>' # move commit down one
    moveUpCommit: '<c-k>' # move commit up one
    amendToCommit: 'A'
    amendAttributeMenu: 'a'
    pickCommit: 'p' # pick commit (when mid-rebase)
    revertCommit: 't'
    cherryPickCopy: 'C'
    pasteCommits: 'V'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitMessageToClipboard: '<c-y>'
    openLogMenu: '<c-l>'
    viewBisectOptions: 'b'
  stash:
    popStash: 'g'
    renameStash: 'r'
  commitFiles:
    checkoutCommitFile: 'c'
  main:
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
  submodules:
    init: 'I'
    update: 'u'
    bulkMenu: 'b'
  commitMessage:
    commitMenu: '<c-o>'
  amendAttribute:
    addCoAuthor: 'c'
    resetAuthor: 'a'
    setAuthor: 'A'
