theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
cursorline = true
color-modes = true
rulers = [80]
bufferline = "always"
jump-label-alphabet = "tsrneiaodhlpfuwymvkz"

[editor.statusline]
left = ["mode", "file-modification-indicator", "version-control", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "total-line-numbers", "file-encoding"]

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
nbsp = "all"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
C-s = ":w"
A-r = ":config-reload"
C-a = "select_all"
r = "insert_mode"
C-r = "insert_at_line_start"
R = "append_mode"
a = ["open_below", "insert_mode"]
A = ["open_above", "insert_mode"]
n = "move_prev_word_start"
N = "extend_prev_word_start"
o = "move_next_word_end"
O = "extend_next_word_end"
i = "move_visual_line_up"
I = "extend_line_above"
e = "move_visual_line_down"
E = "extend_line_below"
# line-up
C-i = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "goto_line_start"]
# line-down
C-e = ["keep_primary_selection","extend_to_line_bounds","delete_selection", "paste_after", "goto_line_start"]
backspace = "delete_selection_noyank"
# delete selected line
S-backspace = ["extend_to_line_bounds", "delete_selection_noyank"]
del = "change_selection_noyank"
# delete selected line and switch to INS mode
S-del = ["extend_to_line_bounds", "delete_selection_noyank", "insert_mode"]
esc = ["collapse_selection", "keep_primary_selection"]
pageup = "half_page_up"
pagedown = "half_page_down"
d = "search"
D = "rsearch"
C-d = "select_regex"
t = "search_next"
T = "search_prev"
C-t = "search_selection"
s = "goto_word"
S = "extend_to_word"
h = "toggle_comments"
c = "copy_selection_on_next_line"
C = "copy_selection_on_prev_line"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_line_up"
S-down = "extend_line_down"
j = "join_selections_space"
m = "indent"
v = "unindent"
"+" = "increment"
"minus" = "decrement"
"," = "switch_to_lowercase"
"<" = "switch_to_uppercase"
"C-," = "switch_case"
# space = "no_op"
# todo: yank, paste, replace with yanked
# jump-list bindings/submenu?
# rmv primary sel
# split selections?

[keys.insert]
C-s = ":w"

